version = 0.1
[default.deploy.parameters]
stack_name = "serverless-appsync-ddb-integration"
resolve_s3 = true
s3_prefix = "serverless-appsync-ddb-integration"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ApiName=\"ProductsAppsyncApi\" TableArn=\"arn:aws:dynamodb:eu-west-1:923125397052:table/ProductsTable\" TableName=\"ProductsTable\""
image_repositories = []
